// DO NOT EDIT: generated by sanrakshya/internal/sourcemetadata/generate/main.go

package sourcemetadata

import "github.com/anubhav06/sanrakshya-cli/sanrakshya/source"

// AllTypes returns a list of all source metadata types that sanrakshya supports (that are represented in the source.Description.Metadata field).
func AllTypes() []any {
	return []any{source.DirectorySourceMetadata{}, source.FileSourceMetadata{}, source.StereoscopeImageSourceMetadata{}}
}
