# Generated by Django 4.2.8 on 2023-12-17 09:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthenticationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(max_length=100)),
                ('created_DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiry_DateTime', models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 41, 13, 908777, tzinfo=datetime.timezone.utc))),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
