# Generated by Django 4.2.8 on 2023-12-17 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_sbomdata_cpe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 9, 42, 24, 668562, tzinfo=datetime.timezone.utc)),
        ),
    ]
