# Generated by Django 4.2.8 on 2023-12-17 11:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_userauthenticationkey_expiry_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 13, 38, 240088, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SBOM_CPEs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPE', models.CharField(max_length=256)),
                ('sbom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbom_cpe', to='app.sbomdata')),
            ],
        ),
    ]
