# Generated by Django 4.2.8 on 2023-12-17 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userauthenticationkey_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sbom_cpes',
            old_name='sbom',
            new_name='sbom_link',
        ),
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 46, 36, 680880, tzinfo=datetime.timezone.utc)),
        ),
    ]
