# Generated by Django 4.2.8 on 2023-12-17 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_sbom_sbom_cpes_sbom_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SBOMcpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPE', models.CharField(max_length=256)),
                ('sbom_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbomCPE', to='app.sbomdata')),
            ],
        ),
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 16, 11, 48, 55, 421176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='SBOM_CPEs',
        ),
    ]
