# Generated by Django 4.2.8 on 2023-12-19 10:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_sbomcpe_alter_userauthenticationkey_expiry_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 10, 46, 36, 86452, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbom_projects', to='app.sbomdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userProjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
