# Generated by Django 4.2.8 on 2023-12-19 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_projects_vulnerability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='high_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='low_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='medium_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vulnerability_projects', to='app.vulnerabilitydata'),
        ),
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 25, 12, 484313, tzinfo=datetime.timezone.utc)),
        ),
    ]
