# Generated by Django 4.2.8 on 2023-12-19 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_projects_high_count_projects_low_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='testproject', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 30, 29, 913344, tzinfo=datetime.timezone.utc)),
        ),
    ]
