# Generated by Django 5.0 on 2023-12-20 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_projects_sbom_remove_projects_vulnerability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 7, 34, 7, 875678, tzinfo=datetime.timezone.utc)),
        ),
    ]
