# Generated by Django 5.0 on 2023-12-20 07:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_userauthenticationkey_expiry_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthenticationkey',
            name='expiry_DateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 7, 51, 15, 764282, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='latest_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PkgName', models.CharField(max_length=100)),
                ('PkgVersion', models.CharField(max_length=100)),
                ('PkgLatestVersion', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_version', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
